server:
  port: 8080
  servlet.context-path: /api/

general:
  db:
    host: localhost
    port: 3306
    databasename: budget
    schemaname: master
    username: legion
    password:

spring:
  application:
    name: support-my-budget
    datasource:
      url: jdbc:mysql://${general.db.host}:${general.db.port}/${general.db.databasename}
      ?currentSchema=${general.db.schemaname}&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=UTF-8
      username: ${general.db.username}
      password: ${general.db.password}
      driver-class-name: com.mysql.jdbc.Driver
      hikari:
        pool-name: ${spring.application.name}-hikari-cp
        maximum-pool-size: 20
        leak-detection-threshold: 60000
    liquibase:
      change-log: classpath:/db/changelog/db-changelog-master.xml
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 50MB
      max-request-size: 50MB